<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <Version>0.0.5</Version>
    <AssemblyVersion>0.0.5.0</AssemblyVersion>
    <FileVersion>0.0.5.0</FileVersion>
    <Product>STORM FELLOWSHIP</Product>
    <Company>STORM FELLOWSHIP</Company>
    <Authors>ReiKatari</Authors>
    <Description>High-performance desktop communication, voice, video and fellowship platform.</Description>
    <Copyright>Copyright © 2026 ReiKatari / STORM</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\**" />
    <Content Include="Assets\AppIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.2" />
  </ItemGroup>
</Project>